#!/bin/bash

DEFAULT_SINK=$(eval pacmd list-sinks | grep -A1 "* index" | grep 'name' | sed "s/</ /" | sed "s/>/ /" | awk '/name/ {print $2}')
SINK_NAME=$sink || $sink2
STATUS=""

mute_sink()
{
    pactl set-sink-mute ${SINK_NAME} toggle
}

set_default_sink_and_move_inputs()
{
    pacmd set-default-sink ${SINK_NAME}
    pacmd list-sink-inputs | awk '/index:/{print $2}' | xargs -r -I{} pacmd move-sink-input {} @DEFAULT_SINK@ || echo 'move sink input failed'
}

get_status()
{
    check_if_idle
    check_if_running
    check_if_muted
}

check_if_running()
{
    RUNNING_SINKS=$(eval pacmd list-sinks | grep -B4 "state: RUNNING" | grep "name" | sed "s/</ /" | sed "s/>/ /" | awk '/name/ {print $2}' | tr '\n' ' ')
    if [[ ${RUNNING_SINKS} == *"${SINK_NAME}"* ]]; then
        STATUS="running"
    fi
}

check_if_muted()
{
    MUTED_SINKS=$(eval pacmd list-sinks | grep -B11 "muted: yes" | grep "name" | sed "s/</ /" | sed "s/>/ /" | grep "name" | awk '/name:/ {print $2}')
    if [[  ${MUTED_SINKS} == *"${SINK_NAME}"* ]]; then
        STATUS="muted"
    fi
}

check_if_idle()                                                                                                 
{                                                                              
    IDLE_SINKS=$(eval pacmd list-sinks | grep -B4 "state: IDLE" | grep "name" | sed "s/</ /" | sed "s/>/ /" | awk '/name/ {print $2}' | tr '\n' ' ') 
    if [[ ${IDLE_SINKS} == *"${SINK_NAME}"* ]]; then                          
        STATUS="idle"
    fi
}

check_if_suspended()                                                                                                 
{                                                                              
    IDLE_SINKS=$(eval pacmd list-sinks | grep -B4 "state: SUSPENDED" | grep "name" | sed "s/</ /" | sed "s/>/ /" | awk '/name/ {print $2}' | tr '\n' ' ') 
    if [[ ${IDLE_SINKS} == *"${SINK_NAME}"* ]]; then                          
        STATUS="suspended"
    fi
}

print_muted_status()
{
    if [[ ${DEFAULT_SINK} == ${SINK_NAME} ]]; then
        echo ' <span foreground="#dba8bc" background="#35e8a3">[<i>MUTED</i>]</span>'
    else
        echo ' <span foreground="#dba8bc">[<i>MUTED</i>]</span>'
    fi
}

print_normal_status()
{
    VOLUME=$(eval pulsemixer --get-volume | awk '{print $1}')
    if [[ ${DEFAULT_SINK} == ${SINK_NAME} ]]; then
        echo ' <span foreground="#000000" background="#35e8a3">'${VOLUME}'%</span>'
    else
        echo ' <span foreground="#898989"><i>'${VOLUME}'%</i></span>'
    fi
}

print_idle_status()
{
    if [[ ${DEFAULT_SINK} == ${SINK_NAME} ]]; then
        echo ' <span foreground="#dba8bc" background="#35e8a3">[<i>idle..</i>]</span>'
    else
        echo ' <span foreground="#dba8bc">[<i>idle..</i>]</span>'
    fi
}


print_suspended_status()
{
    if [[ ${DEFAULT_SINK} == ${SINK_NAME} ]]; then
        echo ' <span foreground="#dba8bc" background="#35e8a3">[<i>SUSPENDED</i>]</span>'
    else
        echo ' <span foreground="#ff0000">[<i>SUSPENDED</i>]</span>'
    fi
}

check_if_idle
check_if_running
check_if_muted
check_if_suspended

case $button in
    1) mute_sink ;;
    2) set_default_sink_and_move_inputs ;;
    3) echo $instance
esac

# echo "Button=$button x=$x y=$y"

case ${STATUS} in
    "suspended") print_suspended_status ;;
    "idle") print_idle_status ;;
    "muted") print_muted_status ;;
    "running") print_normal_status ;;
esac

